In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [11]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive\\Desktop\\PROJECTS\\Car Price Prediction Using Machine Learning\\Datasets\\bmw.csv")

In [13]:
df

model  year  price transmission  mileage fuelType  tax   mpg  \
0       5 Series  2014  11200    Automatic    67068   Diesel  125  57.6   
1       6 Series  2018  27000    Automatic    14827   Petrol  145  42.8   
2       5 Series  2016  16000    Automatic    62794   Diesel  160  51.4   
3       1 Series  2017  12750    Automatic    26676   Diesel  145  72.4   
4       7 Series  2014  14500    Automatic    39554   Diesel  160  50.4   
...          ...   ...    ...          ...      ...      ...  ...   ...   
10776         X3  2016  19000    Automatic    40818   Diesel  150  54.3   
10777   5 Series  2016  14600    Automatic    42947   Diesel  125  60.1   
10778   3 Series  2017  13100       Manual    25468   Petrol  200  42.8   
10779   1 Series  2014   9930    Automatic    45000   Diesel   30  64.2   
10780         X1  2017  15981    Automatic    59432   Diesel  125  57.6   

       engineSize  
0             2.0  
1             2.0  
2             3.0  
3             1.5  
4             3.0  
...           ...  
10776         2.0  
10777         2.0  
10778         2.0  
10779         2.0  
10780         2.0  

[10781 rows x 9 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10781 entries, 0 to 10780
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10781 non-null  object 
 1   year          10781 non-null  int64  
 2   price         10781 non-null  int64  
 3   transmission  10781 non-null  object 
 4   mileage       10781 non-null  int64  
 5   fuelType      10781 non-null  object 
 6   tax           10781 non-null  int64  
 7   mpg           10781 non-null  float64
 8   engineSize    10781 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 758.2+ KB


In [39]:
x = df.iloc[:,[0,1,3,4,5,6,7,8]].values
y = df.iloc[:,[2]].values

In [51]:
x

array([[' 5 Series', 2014, 'Automatic', ..., 125, 57.6, 2.0],
       [' 6 Series', 2018, 'Automatic', ..., 145, 42.8, 2.0],
       [' 5 Series', 2016, 'Automatic', ..., 160, 51.4, 3.0],
       ...,
       [' 3 Series', 2017, 'Manual', ..., 200, 42.8, 2.0],
       [' 1 Series', 2014, 'Automatic', ..., 30, 64.2, 2.0],
       [' X1', 2017, 'Automatic', ..., 125, 57.6, 2.0]], dtype=object)

In [43]:
y

array([[11200],
       [27000],
       [16000],
       ...,
       [13100],
       [ 9930],
       [15981]], dtype=int64)

In [45]:
df['model'].unique()

array([' 5 Series', ' 6 Series', ' 1 Series', ' 7 Series', ' 2 Series',
       ' 4 Series', ' X3', ' 3 Series', ' X5', ' X4', ' i3', ' X1', ' M4',
       ' X2', ' X6', ' 8 Series', ' Z4', ' X7', ' M5', ' i8', ' M2',
       ' M3', ' M6', ' Z3'], dtype=object)

In [47]:
df['transmission'].unique()

array(['Automatic', 'Manual', 'Semi-Auto'], dtype=object)

In [49]:
df['fuelType'].unique()

array(['Diesel', 'Petrol', 'Other', 'Hybrid', 'Electric'], dtype=object)

In [57]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,0] = le1.fit_transform(x[:,0])
le2 = LabelEncoder()
x[:,4] = le2.fit_transform(x[:,4])

In [65]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2])], remainder='passthrough')
x = ct.fit_transform(x)

In [69]:
x

array([[1.0, 0.0, 0.0, ..., 125, 57.6, 2.0],
       [1.0, 0.0, 0.0, ..., 145, 42.8, 2.0],
       [1.0, 0.0, 0.0, ..., 160, 51.4, 3.0],
       ...,
       [0.0, 1.0, 0.0, ..., 200, 42.8, 2.0],
       [1.0, 0.0, 0.0, ..., 30, 64.2, 2.0],
       [1.0, 0.0, 0.0, ..., 125, 57.6, 2.0]], dtype=object)

In [71]:
y

array([[11200],
       [27000],
       [16000],
       ...,
       [13100],
       [ 9930],
       [15981]], dtype=int64)

In [73]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [75]:
x

array([[ 1.41588771, -0.55331238, -0.87352258, ..., -0.10896272,
         0.038326  , -0.30391088],
       [ 1.41588771, -0.55331238, -0.87352258, ...,  0.21619875,
        -0.43398169, -0.30391088],
       [ 1.41588771, -0.55331238, -0.87352258, ...,  0.46006985,
        -0.15953263,  1.50759086],
       ...,
       [-0.7062707 ,  1.80729735, -0.87352258, ...,  1.11039279,
        -0.43398169, -0.30391088],
       [ 1.41588771, -0.55331238, -0.87352258, ..., -1.65347971,
         0.24894971, -0.30391088],
       [ 1.41588771, -0.55331238, -0.87352258, ..., -0.10896272,
         0.038326  , -0.30391088]])

In [77]:
from sklearn.model_selection import train_test_split

In [79]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33, random_state=0)

In [81]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(x_train, y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(random_state=0)

In [83]:
y_pred = rf.predict(x_test)

In [105]:
from sklearn.metrics import r2_score

In [89]:
print(y_test)

[[21980]
 [29500]
 [15989]
 ...
 [14795]
 [26000]
 [24012]]


In [91]:
print(y_pred)

[22336.68       30908.64142857 16487.1        ... 14447.94
 26966.36       22793.93      ]


In [95]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[22336.68       21980.        ]
 [30908.64142857 29500.        ]
 [16487.1        15989.        ]
 ...
 [14447.94       14795.        ]
 [26966.36       26000.        ]
 [22793.93       24012.        ]]


In [101]:
print(r2_score(y_test,y_pred))

0.9267373275591029


In [107]:
my_data = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

In [109]:
dataframe = pd.DataFrame(my_data,columns=['Predicted_value', 'Real_value'])

In [111]:
print(dataframe)

      Predicted_value  Real_value
0        22336.680000     21980.0
1        30908.641429     29500.0
2        16487.100000     15989.0
3        34434.876667     31503.0
4        25884.290000     25940.0
...               ...         ...
3553     14485.640000     13750.0
3554     37112.025000     39950.0
3555     14447.940000     14795.0
3556     26966.360000     26000.0
3557     22793.930000     24012.0

[3558 rows x 2 columns]
